-- Drop existing tables
begin
  execute immediate 'drop table esg_risk_alerts cascade constraints';
exception when others then null;
end;
/
begin
  execute immediate 'drop table esg_supplier_audits cascade constraints';
exception when others then null;
end;
/
begin
  execute immediate 'drop table esg_suppliers cascade constraints';
exception when others then null;
end;
/

-- 1. Suppliers Master Table
create table esg_suppliers (
    id                        number generated by default on null as identity constraint esg_suppliers_id_pk primary key,
    name                      varchar2(120 char) constraint esg_suppliers_name_unq unique not null,
    code                      varchar2(30 char) constraint esg_suppliers_code_unq unique not null,
    country                   varchar2(80 char) not null,
    industry                  varchar2(80 char) not null,
    tier                      varchar2(20 char) not null,
    esg_rating                varchar2(10 char) constraint esg_suppliers_esg_rating_ck check (esg_rating in ('A','B','C','D','F')),
    carbon_intensity_score    number constraint esg_suppliers_carbon_ck check (carbon_intensity_score between 0 and 100),
    financial_risk_index      varchar2(20 char) constraint esg_suppliers_fin_risk_ck check (financial_risk_index in ('Low','Medium','High','Critical')),
    audit_status              varchar2(30 char) constraint esg_suppliers_audit_st_ck check (audit_status in ('Compliant','Pending Audit','Action Required','Non Compliant')),
    primary_contact_email     varchar2(120 char),
    primary_contact_phone     varchar2(40 char),
    contract_annual_value     number(14,2),
    last_audit_date           date,
    next_audit_due_date       date,
    compliance_notes          clob,
    vector_risk_summary       clob,
    created                   date not null,
    created_by                varchar2(255 char) not null,
    updated                   date not null,
    updated_by                varchar2(255 char) not null
);

-- 2. Supplier ESG Audits Table
create table esg_supplier_audits (
    id                      number generated by default on null as identity constraint esg_supplier_audits_id_pk primary key,
    supplier_id             number constraint esg_supplier_audits_supplier_id_fk references esg_suppliers on delete cascade not null,
    audit_year              number(4) not null,
    auditor_name            varchar2(100 char) not null,
    scope1_co2_tonnes       number(10,2),
    scope2_co2_tonnes       number(10,2),
    scope3_co2_tonnes       number(10,2),
    renewable_energy_pct    number(5,2) constraint esg_audits_renew_ck check (renewable_energy_pct between 0 and 100),
    labor_ethics_score      number(5,2) constraint esg_audits_labor_ck check (labor_ethics_score between 0 and 100),
    governance_score        number(5,2) constraint esg_audits_gov_ck check (governance_score between 0 and 100),
    composite_esg_score     number(5,2) constraint esg_audits_composite_ck check (composite_esg_score between 0 and 100),
    audit_verdict           varchar2(30 char) constraint esg_audits_verdict_ck check (audit_verdict in ('Passed','Conditional Pass','Failed')),
    corrective_actions      clob,
    created                 date not null,
    created_by              varchar2(255 char) not null,
    updated                 date not null,
    updated_by              varchar2(255 char) not null
);

create index esg_supplier_audits_i1 on esg_supplier_audits (supplier_id);

-- 3. ESG & Supply Chain Risk Alerts Table
create table esg_risk_alerts (
    id                   number generated by default on null as identity constraint esg_risk_alerts_id_pk primary key,
    supplier_id          number constraint esg_risk_alerts_supplier_id_fk references esg_suppliers on delete cascade not null,
    alert_date           timestamp default systimestamp,
    alert_severity       varchar2(20 char) constraint esg_alerts_sev_ck check (alert_severity in ('Critical','Warning','Info')),
    alert_type           varchar2(50 char) not null,
    alert_headline       varchar2(255 char) not null,
    alert_description    clob,
    is_resolved_yn       varchar2(1 char) default 'N' constraint esg_alerts_resolved_ck check (is_resolved_yn in ('Y','N')),
    created              date not null,
    created_by           varchar2(255 char) not null,
    updated              date not null,
    updated_by           varchar2(255 char) not null
);

create index esg_risk_alerts_i1 on esg_risk_alerts (supplier_id);

-- Triggers for Audit Columns
create or replace trigger esg_suppliers_biu
    before insert or update on esg_suppliers
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end esg_suppliers_biu;
/

create or replace trigger esg_supplier_audits_biu
    before insert or update on esg_supplier_audits
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end esg_supplier_audits_biu;
/

create or replace trigger esg_risk_alerts_biu
    before insert or update on esg_risk_alerts
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end esg_risk_alerts_biu;
/

-- Sample Data Inserts
insert into esg_suppliers (id, name, code, country, industry, tier, esg_rating, carbon_intensity_score, financial_risk_index, audit_status, primary_contact_email, primary_contact_phone, contract_annual_value, last_audit_date, next_audit_due_date, compliance_notes, vector_risk_summary)
values (1, 'Apex Microelectronics Inc', 'SUP-1001', 'United States', 'Electronics', 'Tier 1', 'A', 22.5, 'Low', 'Compliant', 'esg@apexmicro.com', '+1-408-555-0192', 4500000.00, sysdate-120, sysdate+245, 'Gold standard CSRD compliance. 100% renewable silicon fab operations in Oregon.', 'Low risk profile. Exemplary clean energy transition and fair labor practices across fab facilities.');

insert into esg_suppliers (id, name, code, country, industry, tier, esg_rating, carbon_intensity_score, financial_risk_index, audit_status, primary_contact_email, primary_contact_phone, contract_annual_value, last_audit_date, next_audit_due_date, compliance_notes, vector_risk_summary)
values (2, 'Nordic Clean Energy AB', 'SUP-1002', 'Sweden', 'Energy', 'Tier 1', 'A', 14.8, 'Low', 'Compliant', 'audit@nordicenergy.se', '+46-8-123-4567', 7200000.00, sysdate-45, sysdate+320, 'Zero-carbon hydro and wind grid provider with ISO 14001 certification.', 'Top tier ESG benchmark in Scope 1 and Scope 2 decarbonization.');

insert into esg_suppliers (id, name, code, country, industry, tier, esg_rating, carbon_intensity_score, financial_risk_index, audit_status, primary_contact_email, primary_contact_phone, contract_annual_value, last_audit_date, next_audit_due_date, compliance_notes, vector_risk_summary)
values (3, 'Bavaria Automotive Logistics GmbH', 'SUP-1003', 'Germany', 'Automotive', 'Tier 1', 'B', 48.0, 'Medium', 'Compliant', 'compliance@bavaria-logistics.de', '+49-89-9876-543', 3800000.00, sysdate-210, sysdate+155, 'Electric fleet conversion at 65%. On track for 2027 net-zero freight corridor.', 'Moderate carbon exposure during peak European shipping quarters.');

insert into esg_suppliers (id, name, code, country, industry, tier, esg_rating, carbon_intensity_score, financial_risk_index, audit_status, primary_contact_email, primary_contact_phone, contract_annual_value, last_audit_date, next_audit_due_date, compliance_notes, vector_risk_summary)
values (4, 'Kyoto Precision Optics Corp', 'SUP-1004', 'Japan', 'Manufacturing', 'Tier 2', 'B', 39.5, 'Low', 'Compliant', 'contact@kyoto-optics.jp', '+81-75-333-8888', 2100000.00, sysdate-90, sysdate+275, 'Water recycling index above 90%. RoHS and REACH chemical protocols strictly adhered.', 'Solid governance score with continuous water reclamation improvements.');

insert into esg_suppliers (id, name, code, country, industry, tier, esg_rating, carbon_intensity_score, financial_risk_index, audit_status, primary_contact_email, primary_contact_phone, contract_annual_value, last_audit_date, next_audit_due_date, compliance_notes, vector_risk_summary)
values (5, 'SinoTech Semiconductor Ltd', 'SUP-1005', 'Taiwan', 'Electronics', 'Tier 1', 'C', 68.2, 'Medium', 'Pending Audit', 'risk@sinotech-semi.tw', '+886-3-555-7777', 8900000.00, sysdate-350, sysdate+15, 'High thermal load reported in Q3. Pending on-site water usage audit.', 'Elevated carbon intensity due to grid reliance on coal-fired power plants.');

insert into esg_suppliers (id, name, code, country, industry, tier, esg_rating, carbon_intensity_score, financial_risk_index, audit_status, primary_contact_email, primary_contact_phone, contract_annual_value, last_audit_date, next_audit_due_date, compliance_notes, vector_risk_summary)
values (6, 'Valence Battery Dynamics', 'SUP-1006', 'South Korea', 'Energy', 'Tier 2', 'B', 44.1, 'Low', 'Compliant', 'sustainability@valence-battery.kr', '+82-2-777-9900', 5400000.00, sysdate-60, sysdate+305, 'Responsible cobalt sourcing certified by RBA (Responsible Business Alliance).', 'Reliable supply chain traceability for cathode raw materials.');

insert into esg_suppliers (id, name, code, country, industry, tier, esg_rating, carbon_intensity_score, financial_risk_index, audit_status, primary_contact_email, primary_contact_phone, contract_annual_value, last_audit_date, next_audit_due_date, compliance_notes, vector_risk_summary)
values (7, 'Atlas Global Freight Lines', 'SUP-1007', 'Panama', 'Manufacturing', 'Tier 2', 'D', 82.7, 'High', 'Action Required', 'ops@atlasfreight.pa', '+507-200-1122', 1750000.00, sysdate-400, sysdate-35, 'Overdue maritime emissions inspection. Heavy fuel oil bunker compliance pending.', 'High risk alert: Maritime sulfur cap compliance gap and delayed decarbonization roadmap.');

insert into esg_suppliers (id, name, code, country, industry, tier, esg_rating, carbon_intensity_score, financial_risk_index, audit_status, primary_contact_email, primary_contact_phone, contract_annual_value, last_audit_date, next_audit_due_date, compliance_notes, vector_risk_summary)
values (8, 'Zenith Chemical Solutions', 'SUP-1008', 'India', 'Healthcare', 'Tier 3', 'F', 91.4, 'Critical', 'Non Compliant', 'safety@zenith-chem.in', '+91-22-6600-4400', 950000.00, sysdate-420, sysdate-55, 'Effluent treatment plant malfunction in Maharashtra facility. Regulatory notice issued.', 'Critical hazard rating: Wastewater discharge breach and failure to provide Scope 3 data.');

insert into esg_suppliers (id, name, code, country, industry, tier, esg_rating, carbon_intensity_score, financial_risk_index, audit_status, primary_contact_email, primary_contact_phone, contract_annual_value, last_audit_date, next_audit_due_date, compliance_notes, vector_risk_summary)
values (9, 'Verde Packaging Solutions', 'SUP-1009', 'Spain', 'Retail', 'Tier 2', 'A', 18.0, 'Low', 'Compliant', 'eco@verdepack.es', '+34-91-888-2233', 1200000.00, sysdate-30, sysdate+335, '100% biodegradable polymers and FSC-certified pulp packaging materials.', 'Best-in-class circular economy metrics across all packaging lines.');

insert into esg_suppliers (id, name, code, country, industry, tier, esg_rating, carbon_intensity_score, financial_risk_index, audit_status, primary_contact_email, primary_contact_phone, contract_annual_value, last_audit_date, next_audit_due_date, compliance_notes, vector_risk_summary)
values (10, 'Cascade BioFuels Corp', 'SUP-1010', 'Canada', 'Energy', 'Tier 1', 'B', 31.0, 'Low', 'Compliant', 'info@cascadebiofuels.ca', '+1-604-555-3456', 3100000.00, sysdate-150, sysdate+215, 'Second-generation agricultural waste biofuel feedstocks. ISCC certified.', 'Strong renewable credit score with low lifecycle carbon impact.');

-- Sample Audits
insert into esg_supplier_audits (supplier_id, audit_year, auditor_name, scope1_co2_tonnes, scope2_co2_tonnes, scope3_co2_tonnes, renewable_energy_pct, labor_ethics_score, governance_score, composite_esg_score, audit_verdict, corrective_actions)
values (1, 2025, 'SGS Environmental Services', 120.50, 45.00, 310.00, 94.50, 98.00, 95.00, 95.80, 'Passed', 'Continue rooftop solar expansion across Building 3.');

insert into esg_supplier_audits (supplier_id, audit_year, auditor_name, scope1_co2_tonnes, scope2_co2_tonnes, scope3_co2_tonnes, renewable_energy_pct, labor_ethics_score, governance_score, composite_esg_score, audit_verdict, corrective_actions)
values (5, 2025, 'TUV Rheinland', 1420.00, 890.00, 3200.00, 38.00, 82.00, 78.00, 66.00, 'Conditional Pass', 'Install heat recovery scrubbers and submit Scope 2 reduction plan within 60 days.');

insert into esg_supplier_audits (supplier_id, audit_year, auditor_name, scope1_co2_tonnes, scope2_co2_tonnes, scope3_co2_tonnes, renewable_energy_pct, labor_ethics_score, governance_score, composite_esg_score, audit_verdict, corrective_actions)
values (8, 2025, 'Bureau Veritas', 3100.00, 1850.00, 6800.00, 12.00, 45.00, 50.00, 35.60, 'Failed', 'Cease uncontrolled wastewater discharge immediately. Upgrade ETP filtration systems.');

-- Sample Risk Alerts
insert into esg_risk_alerts (supplier_id, alert_date, alert_severity, alert_type, alert_headline, alert_description, is_resolved_yn)
values (8, systimestamp - interval '2' day, 'Critical', 'Sanction Risk', 'Pollution Control Board Violation Notice', 'Maharashtra regulatory body issued a show-cause notice regarding industrial wastewater effluent.', 'N');

insert into esg_risk_alerts (supplier_id, alert_date, alert_severity, alert_type, alert_headline, alert_description, is_resolved_yn)
values (7, systimestamp - interval '5' day, 'Warning', 'Audit Overdue', 'Annual Maritime Emission Audit Overdue by 35 Days', 'Supplier has not submitted third-party bunker fuel certification for Q4.', 'N');

insert into esg_risk_alerts (supplier_id, alert_date, alert_severity, alert_type, alert_headline, alert_description, is_resolved_yn)
values (5, systimestamp - interval '10' day, 'Warning', 'Carbon Spike', 'Quarterly Scope 2 Emissions Exceeded Baseline by 18%', 'Peak summer cooling requirements triggered auxiliary fossil generator usage.', 'N');

commit;
