-- ==============================================================================
-- APEXLang Quick SQL Specification: Autonomous Supplier Risk & ESG Hub
-- Generated by: IBM Consulting Advantage (ICA) Edge
-- Target: Oracle APEX 24.x / 26.x
-- ==============================================================================

# settings = { prefix: "ESG", pk: "IDENTITY", auditcols: true, semantics: "CHAR", language: "en", drop: true }

suppliers /insert 15
  name vc100 /nn /unique
  code vc20 /nn /unique
  country vc60 /nn
  industry vc80 /values Automotive, Energy, Electronics, Healthcare, Manufacturing, Retail
  tier vc20 /values Tier 1, Tier 2, Tier 3
  esg_rating vc10 /check in ('A', 'B', 'C', 'D', 'F') /values A, B, C, D, F
  carbon_intensity_score num /check between 0 and 100
  financial_risk_index vc20 /values High, Medium, Low
  audit_status vc30 /values Compliant, Pending Audit, Action Required, Non Compliant
  primary_contact_email vc120
  primary_contact_phone vc40
  contract_annual_value num(14,2)
  last_audit_date date
  next_audit_due_date date
  compliance_notes clob
  vector_risk_summary clob

supplier_audits /insert 25
  supplier_id /fk suppliers /nn
  audit_year num(4) /nn
  auditor_name vc100 /nn
  scope1_co2_tonnes num(10,2)
  scope2_co2_tonnes num(10,2)
  scope3_co2_tonnes num(10,2)
  renewable_energy_pct num(5,2) /check between 0 and 100
  labor_ethics_score num(5,2) /check between 0 and 100
  governance_score num(5,2) /check between 0 and 100
  composite_esg_score num(5,2) /check between 0 and 100
  audit_verdict vc30 /values Passed, Conditional Pass, Failed
  corrective_actions clob

risk_alerts /insert 10
  supplier_id /fk suppliers /nn
  alert_date timestamp default systimestamp
  alert_severity vc20 /values Critical, Warning, Info
  alert_type vc50 /values Carbon Spike, Credit Downgrade, Sanction Risk, Audit Overdue
  alert_headline vc255 /nn
  alert_description clob
  is_resolved_yn vc1 /default 'N' /values Y, N
